loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - loki.desafio-globo
  path: /
  pathType: Prefix
  tls: []
